DEFAULT_RULES = [
    {
        "code": "R001",
        "name": "Pago duplicado exacto",
        "module": "purchases",
        "description": "Detecta pagos del mismo proveedor, factura y monto en fechas iguales o cercanas.",
        "risk_level_default": "high",
        "config_json": {"near_days": 2},
    },
    {
        "code": "R002",
        "name": "Factura duplicada",
        "module": "purchases",
        "description": "Detecta facturas repetidas por proveedor, numero e importe.",
        "risk_level_default": "high",
        "config_json": {},
    },
    {
        "code": "R003",
        "name": "Proveedores con misma cuenta bancaria",
        "module": "suppliers",
        "description": "Detecta proveedores distintos que comparten cuenta bancaria.",
        "risk_level_default": "medium",
        "config_json": {},
    },
    {
        "code": "R004",
        "name": "Proveedor nuevo con pagos altos",
        "module": "purchases",
        "description": "Detecta proveedores recientes con pagos acumulados altos.",
        "risk_level_default": "high",
        "config_json": {"days": 30, "amount_threshold": 1000000},
    },
    {
        "code": "R005",
        "name": "Pago o factura sin orden de compra",
        "module": "purchases",
        "description": "Detecta facturas sin orden o pagos sin factura asociada.",
        "risk_level_default": "medium",
        "config_json": {},
    },
    {
        "code": "R006",
        "name": "Compra fraccionada",
        "module": "purchases",
        "description": "Detecta compras repetidas justo debajo del limite de aprobacion.",
        "risk_level_default": "high",
        "config_json": {"approval_limit": 500000, "lower_ratio": 0.9, "window_days": 7},
    },
    {
        "code": "R007",
        "name": "Aprobador igual al solicitante",
        "module": "purchases",
        "description": "Detecta ordenes donde la misma persona solicita y aprueba.",
        "risk_level_default": "medium",
        "config_json": {},
    },
    {
        "code": "R008",
        "name": "Concentracion excesiva en proveedor",
        "module": "purchases",
        "description": "Detecta proveedores que concentran demasiado gasto.",
        "risk_level_default": "medium",
        "config_json": {"share_threshold": 0.5},
    },
    {
        "code": "R009",
        "name": "Pago fuera de horario o dia no laboral",
        "module": "purchases",
        "description": "Detecta pagos registrados fuera del horario laboral o en fin de semana.",
        "risk_level_default": "medium",
        "config_json": {"start_hour": 8, "end_hour": 19},
    },
    {
        "code": "R010",
        "name": "Proveedor con datos incompletos",
        "module": "suppliers",
        "description": "Detecta proveedores con datos fiscales, bancarios o de contacto faltantes.",
        "risk_level_default": "low",
        "config_json": {},
    },
    {
        "code": "S001",
        "name": "Ajustes manuales repetidos",
        "module": "inventory",
        "description": "Detecta productos con muchos ajustes manuales en una ventana corta.",
        "risk_level_default": "medium",
        "config_json": {"window_days": 15, "min_adjustments": 3},
    },
    {
        "code": "S002",
        "name": "Stock negativo",
        "module": "inventory",
        "description": "Detecta productos cuyo stock calculado queda por debajo de cero.",
        "risk_level_default": "high",
        "config_json": {},
    },
    {
        "code": "S003",
        "name": "Diferencia entre stock esperado y fisico",
        "module": "inventory",
        "description": "Detecta diferencias relevantes entre stock esperado y conteo fisico.",
        "risk_level_default": "medium",
        "config_json": {"quantity_threshold": 20},
    },
    {
        "code": "S004",
        "name": "Movimiento fuera de horario",
        "module": "inventory",
        "description": "Detecta movimientos de stock fuera del horario laboral o en fin de semana.",
        "risk_level_default": "medium",
        "config_json": {"start_hour": 8, "end_hour": 19},
    },
    {
        "code": "S005",
        "name": "Merma excesiva",
        "module": "inventory",
        "description": "Detecta salidas o ajustes negativos superiores al umbral esperado.",
        "risk_level_default": "high",
        "config_json": {"quantity_threshold": 50},
    },
    {
        "code": "S006",
        "name": "Transferencia no conciliada",
        "module": "inventory",
        "description": "Detecta transferencias sin contraparte esperada.",
        "risk_level_default": "medium",
        "config_json": {},
    },
    {
        "code": "S007",
        "name": "Usuario con demasiados ajustes",
        "module": "inventory",
        "description": "Detecta operadores con cantidad inusual de ajustes de stock.",
        "risk_level_default": "medium",
        "config_json": {"min_adjustments": 3},
    },
    {
        "code": "S008",
        "name": "Producto critico sin movimiento esperado",
        "module": "inventory",
        "description": "Detecta productos activos sin movimientos durante un periodo relevante.",
        "risk_level_default": "low",
        "config_json": {"days_without_movement": 30},
    },
]
